### ISSUE TITLE
Flickering, grey frames and low FPS when encoding gifs

### ISSUE THREAD

**Issue by RuyiLi** [RuyiLi/image-splitter#1]
When attempting to split certain gifs, some flickering grey pixels will appear on most of the frames. Additionally, the delay option to set the delay in milliseconds between consecutive frames does not work.

## Steps to reproduce:
1. Upload this gif:
![yum](https://user-images.githubusercontent.com/16544254/66615762-f7b80000-eb9b-11e9-8bfb-8c81c25e501d.gif)
2. Change the delay option to 10 milliseconds.
3. Click the split button.

Expected behavior:
1. The roduced gif looks exactly the same as the decoded gif.
2. The delay between each frame is 10 milliseconds.

What actually happens:
1. The produced gif is covered in grey pixels.
![image](https://user-images.githubusercontent.com/16544254/66615833-5c735a80-eb9c-11e9-8a48-7be3cf8ac056.png)
2. The delay between each frame is much longer than 10 milliseconds.

Notes:
- The "grey" color is #36393F, the same as Discord's background. This value is set as the filler background for gifs that have sizes that cannot be split perfectly into square tiles, so perhaps it is more accurate to say that "most of the pixels in the gif's frames are not rendering".

**Comment by ThomasLuu00** [comment]
I would like to look into this issue

**Comment by RuyiLi** [comment]
The issue with the flickering pixels in the preview has been resolved by #2 (Thanks, @ThomasLuu00!), but the frame delay issue still remains.

**Comment by ThomasLuu00** [comment]
So it seems like there is a browser specific frame-rate lower limit for gifs. 
[https://github.com/jnordberg/gif.js/issues/17](url)
I downloaded the encoded gifs and the delay looks fine.

**Comment by RuyiLi** [comment]
Oh, that's unfortunate. I guess an alternative could just be to use multiple canvases to act as placeholders for the actual gifs in the preview.
